name: Standard (Ruby Linter)

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true 
    - name: Install gems
      run: |
        gem install standardrb
    - name: Run standard
      run: standardrb
